/**
 * Histone.js - Histone template engine.
 * version: 3.1.20
 * template: global
 * language(s): no
 * Copyright 2018 MegaFon
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
var Histone = (function(){var Histone;var aa=/\/\//g,ba=/([^\/]*)$/,ca=/([.?*+^$[\]\\(){}|-])/g,da=/^(([^:\/?#]+):)?(\/\/([^\/?#]*))?([^?\#]*)(\?([^#]*))?(#(.*))?/,ea=/^\s*([-+])?(?:(?:0[xX]([0-9A-Fa-f]+))|(?:0[bB]([0-1]+))|((?:[0-9]*\.)?[0-9]+(?:[eE][+-]?[0-9]+)?))\s*$/;function h(a){return'number'===typeof a&&isFinite(a)}var fa='isInteger'in Number?Number.isInteger:function(a){return h(a)&&!(a%1)};
function ga(a){if('string'===typeof a&&(a=a.match(ea))){var b='-'===a[1];a[4]?a=parseFloat(a[4]):a[2]?a=parseInt(a[2],16):a[3]&&(a=parseInt(a[3],2));if(h(a))return b&&(a=-a),a}}function n(a,b,c,d){function e(){f+=1;if(g){for(g=!1;0<f;)--f,a((e.g+=d)<=c?e:null,e.g);g=!0}}3>arguments.length&&(c=Infinity);b||(b=0);d||(d=1);var f=0,g=!0;e.g=-d+b;e()}function p(a){return'string'===typeof a}var q='isArray'in Array?Array.isArray:function(a){return a instanceof Array};
function r(a){return'function'===typeof a}function ha(a){if(!p(a))return{};a=a.match(da);return{scheme:a[1]?a[2]:null,u:a[3]?a[4]:null,path:a[5],query:a[6]?a[7]:null,J:a[8]?a[9]:null}}
function ia(a,b){var c='',d,e,f,g;a=ha(a);b=ha(b);d=a.scheme;e=a.u;f=a.path;g=a.query;var k=a.J,m=b.scheme,l=b.u,u=b.path,x=b.query;p(d)||(p(e)?d=m:''===f?(d=m,e=l,f=u,g=p(g)?g:x):'/'===f[0]?(d=m,e=l):p(l)&&''===u?(d=m,e=l,f='/'+f):(d=m,e=l,f=u.replace(ba,'')+f));p(d)&&(c+=d.toLowerCase()+':');p(e)&&(c+='//'+e);x=f.replace(aa,'/');if('/'===x)x='/';else{d=0;f=[];u=x.split('/');e='/'===x[0]?'/':'';for(l='/'===x.slice(-1)?'/':'';u.length;)switch(x=u.shift()){case '':case '.':break;case '..':f.length?
f.pop():d++;break;default:f.push(x)}if(!e){for(;d--;)f.unshift('..');f.length||f.push('.')}x=e+f.join('/')+l}c+=x;g&&(c+='?'+g);k&&(c+='#'+k);return c}function ja(a){if(p(a))return a.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}function ka(a,b){var c=new Date([('0000'+a).slice(-4),('00'+b).slice(-2),'01'].join('-'));return-(c.getTime()-c.setMonth(b))/864E5}
function la(a,b){p(b)&&b.replace(/((?:[+-]\d+)|\^|\$)([YMWDhms])/g,function(b,d,e){'+'===d[0]||'-'===d[0]?d='+'===d[0]?parseInt(d.slice(1),10):-parseInt(d.slice(1),10):e=d+e;switch(e){case '^Y':a.setMonth(0);a.setDate(1);a.setHours(0);a.setMinutes(0);a.setSeconds(0);break;case '^M':a.setDate(1);a.setHours(0);a.setMinutes(0);a.setSeconds(0);break;case '^W':a.setDate(a.getDate()-((a.getDay()||7)-1));a.setHours(0);a.setMinutes(0);a.setSeconds(0);break;case '^D':a.setHours(0);a.setMinutes(0);a.setSeconds(0);
break;case '^h':a.setMinutes(0);a.setSeconds(0);break;case '^m':a.setSeconds(0);break;case '$Y':a.setMonth(11);a.setDate(31);a.setHours(23);a.setMinutes(59);a.setSeconds(59);break;case '$M':a.setDate(ka(a.getFullYear(),a.getMonth()+1));a.setHours(23);a.setMinutes(59);a.setSeconds(59);break;case '$W':a.setDate(a.getDate()+(7-(a.getDay()||7)));a.setHours(23);a.setMinutes(59);a.setSeconds(59);break;case '$D':a.setHours(23);a.setMinutes(59);a.setSeconds(59);break;case '$h':a.setMinutes(59);a.setSeconds(59);
break;case '$m':a.setSeconds(59);break;case 'Y':a.setFullYear(a.getFullYear()+d);break;case 'M':a.setMonth(a.getMonth()+d);break;case 'W':a.setDate(a.getDate()+7*d);break;case 'D':a.setDate(a.getDate()+d);break;case 'h':a.setHours(a.getHours()+d);break;case 'm':a.setMinutes(a.getMinutes()+d);break;case 's':a.setSeconds(a.getSeconds()+d)}});return a};function t(){}function ma(){}function na(){}function oa(){}ma.prototype=Object.create(t.prototype);na.prototype=Object.create(t.prototype);oa.prototype=Object.create(t.prototype);var pa=new ma,qa=new na,ra=new oa,sa=new function(){};function ta(){};function v(){this.j=[];this.l=[];this.size=0}v.prototype.values=function(){return[].concat(this.l)};v.prototype.keys=function(){return[].concat(this.j)};v.prototype.set=function(a,b){var c=this.j,d=c.indexOf(a);-1===d?(c.push(a),this.size=this.l.push(b)):this.l[d]=b};v.prototype.has=function(a){return-1!==this.j.indexOf(a)};v.prototype.get=function(a){a=this.j.indexOf(a);if(-1!==a)return this.l[a]};
v.prototype['delete']=function(a){var b=this.j;a=b.indexOf(a);-1!==a&&(b.splice(a,1),this.l.splice(a,1),this.size=b.length)};v.prototype.clear=function(){this.j=[];this.l=[];this.size=0};function w(){};function ua(){};function va(){};function y(a,b,c){this.W=a;this.body=b;this.scope=c;this.I=[]}y.prototype.toJavaScript=function(a){var b=this;return function(){var c=Array.prototype.slice.call(arguments),d=c.pop();if(r(d))b.call(c,null,function(b){d(a(b))});else return c.push(d),b.call(c,null,function(a){d=a}),a(d)}};y.prototype.clone=function(){var a=new y,b;for(b in this)this.hasOwnProperty(b)&&(a[b]=this[b]);return a};y.prototype.bind=function(a){if(q(a)&&a.length){var b=this.clone();b.I=a.concat(b.I);return b}return this};
y.prototype.call=function(a,b,c,d){var e=this.body,f=this.W,g=this.scope.extend();a=this.I.concat(a);b={callee:this,caller:(b||g).baseURI,arguments:a};if('object'===typeof d)for(var k in d)d.hasOwnProperty(k)&&(b[k]=d[k]);z(g,b,0,!1);for(d=0;d<f.length;d++)'undefined'===typeof a[d]?z(g,f[d],d+1,!0):z(g,a[d],d+1,!1);r(e)&&(e=e(a));A(e,g,c)};function B(){this.H=0;this.c=new v}B.prototype.map=function(a,b){var c=this,d,e,f=this.getKeys(),g=this.getValues(),k=new B;if(r(b))n(function(m,l){m?(d=f[l],e||(e=function(a){return k.set(a,d),m()}),a(g[l],e,d,c)):b(k)},0,g.length-1);else{for(;f.length;)k.set(a(g.shift(),f.shift()));return k}};B.prototype.filter=function(a,b){var c=this,d,e,f,g=this.getKeys(),k=this.getValues(),m=new B;n(function(l,u){l?(d=g[u],e=k[u],f||(f=function(a){return a&&m.set(e,d),l()}),a(e,f,d,c)):b(m)},0,k.length-1)};
B.prototype.some=function(a,b){var c=this,d,e=this.getKeys(),f=this.getValues();n(function(g,k){g?(d||(d=function(a){return a?b(!0):g()}),a(f[k],d,e[k],c)):b(!1)},0,f.length-1)};B.prototype.every=function(a,b){var c=this,d,e=this.getKeys(),f=this.getValues();n(function(g,k){g?(d||(d=function(a){return a?g():b(!1)}),a(f[k],d,e[k],c)):b(!0)},0,f.length-1)};
B.prototype.clone=function(){for(var a,b=this.c.keys(),c=this.c.values(),d=new B;b.length;)a=c.shift(),a instanceof B&&(a=a.clone()),d.set(a,b.shift());return d};B.prototype.isMap=function(){for(var a=this.getKeys(),b=0;b<a.length;b++)if(a[b]!==String(b))return!0;return!1};B.prototype.isArray=function(){return!this.isMap()};B.prototype.getLength=function(){return this.c.size};B.prototype.has=function(a){return this.c.has(String(a))};B.prototype.get=function(a){return this.c.get(String(a))};
B.prototype.set=function(a,b){var c=ga(b);fa(c)&&0<=c?this.H=Math.max(this.H,(b=c)+1):'undefined'===typeof b&&(b=this.H++);this.c.set(String(b),a);return a};function wa(a,b){var c=a.c.size-1,d=a.getKeys(),e=a.getValues();n(function(a,g){a?b(a,e[g],d[g],g,c):b()},0,c)}
B.prototype.concat=function(){for(var a,b=!1,c=[],d=[],e=new B,f=[this].concat(Array.prototype.slice.call(arguments));f.length;)(a=f.shift())instanceof B&&(a.isMap()&&(b=!0),c=c.concat(a.getKeys()),d=d.concat(a.getValues()));for(;d.length;)b?e.set(d.shift(),c.shift()):e.set(d.shift());return e};
B.prototype.toJavaScript=function(a){var b,c,d,e=0,f=[],g=!0,k=this.getKeys(),m=this.getValues();for(b=0;b<m.length;b++)if(c=k[b],d=a(m[b]),g?f.push(d):f[c]=d,g&&c!==String(e++)){g={};for(e=0;e<f.length;e++)g[k[e]]=f[e];f=g;g=!1}return f};B.prototype.getFirst=function(){return this.c.values()[0]};B.prototype.getLast=function(){var a=this.c.values();return a[a.length-1]};B.prototype.getValues=function(){return this.c.values()};B.prototype.getKeys=function(){return this.c.keys()};function C(){B.apply(this,arguments);this.set('3.1.20','version');try{this.set(this===window&&'browser','server')}catch(a){this.set('nodejs','server')}this.set(!0,'parser')}C.prototype=Object.create(B.prototype);C.prototype.constructor=C;function D(a){B.apply(this,arguments);var b=Array.prototype.slice.call(arguments),b=la(b[0]instanceof Date?b.shift():new Date,b.shift());this.set(b.getDate(),'day');this.set(b.getMonth()+1,'month');this.set(b.getFullYear(),'year');this.set(b.getHours(),'hour');this.set(b.getMinutes(),'minute');this.set(b.getSeconds(),'second')}D.prototype=Object.create(B.prototype);D.prototype.constructor=D;
D.prototype.toJavaScript=function(){var a=new Date;a.setFullYear(this.get('year'));a.setMonth(this.get('month')-1);a.setDate(this.get('day'));a.setHours(this.get('hour'));a.setMinutes(this.get('minute'));a.setSeconds(this.get('second'));a.setMilliseconds(0);return a};var E=new v;E.set(w.prototype,{});E.set(ua.prototype,{});E.set(va.prototype,{});E.set(Boolean.prototype,{});E.set(Number.prototype,{});E.set(String.prototype,{});E.set(RegExp.prototype,{});E.set(y.prototype,{});E.set(B.prototype,{});E.set(D.prototype,{});E.set(C.prototype,{});function xa(a){return a instanceof t?1:a instanceof ta?2:a instanceof Function?3:4}function ya(a,b){return xa(a)-xa(b)}
function za(a){switch(typeof a){case 'boolean':return Boolean.prototype;case 'number':return isFinite(a)?Number.prototype:ua.prototype;case 'string':return String.prototype;default:return Object.getPrototypeOf(a)}}function Aa(a){return null===a?va.prototype:'undefined'===typeof a?ua.prototype:za(a)}
function Ba(a,b,c){var d;q(b)?(a=b[0],b=b[1]):a=Aa(a);E.has(a)||(a=ua.prototype);for(;;){d=E.get(a);if(d.hasOwnProperty(b))return c?!0:d[b];if(a===w.prototype)return c?!1:[0];E.has(a=za(a))||(a=w.prototype)}}
function F(a,b,c,d,e){var f=Ba(a=G(a),b),g=f[0],k=f[2],f=f[1];if(!r(f))return f===sa&&(f=a),e?e(f,g):f;if(3>arguments.length)c=[];else if(!q(c))c=[k?F(c,2):G(c)];else if(c.length){c=[].concat(c);for(var m=0;m<c.length;m++)c[m]=k?F(c[m],2):G(c[m])}if(e)4>f.length?e(f(a,c,d),g):f(a,c,d,function(a,b){h(b)&&0<=b||(b=g);e(a,b)});else return f(a,c,d)}
function Ca(a,b){var c=Array.prototype.slice.call(arguments,2).sort(ya),d=c[0]instanceof t?c.shift()===pa:!1,e=c[0]instanceof ta?c.shift():void 0,f=c[0]instanceof Function?c.shift():void 0;1!==c.length||q(c=c[0])||(c=[c]);if(f)F(a,b,c,e,function(a,b){a=d?F(a,2):G(a);f(a,b)});else return c=F(a,b,c,e),c=d?F(c,2):G(c)}
function H(a,b,c,d,e){if(!(a instanceof Object))return!1;E.has(a)?a=E.get(a):E.set(a,a={});d instanceof t&&(d=[e,e=d][0]);c===sa||r(c)||e||(c=G(c));h(d)&&0<=d||(d=0);return a[String(b)]=[d,c,e===pa],!0}function G(a){'number'!==typeof a||isFinite(a)||(a=void 0);if(E.has(Aa(a)))return a;if(a instanceof Date)return new D(a);var b,c=new B;if(q(a))for(b=0;b<a.length;b++)c.set(G(a[b]));else for(b in a)a.hasOwnProperty(b)&&c.set(G(a[b]),b);return c}function Da(a){return F(a,'toJSON')}
function I(a){return F(a,'toBoolean')}function J(a){return F(a,'toString')}function Ea(a){return F(a,2)}function K(a,b){a=F(a,'toNumber');return h(a)?a:b}var Fa=new C,Ga=Boolean,Ha=Number,Ia=String,Ja=RegExp;function L(a,b,c){if(fa(a=F(a,'toNumber')))return h(b)&&a<b||h(c)&&a>c?void 0:a};function Ka(a){this.baseURI=a;this.s=[];this.K=[];this.o=[];this.m=[[]];M(this)}function La(a){var b=N;b.o.unshift(a,b.s.length-1)}Ka.prototype.B=function(a){var b=this.m;arguments.length?b.unshift([a].concat(b[0])):b.unshift([])};Ka.prototype.C=function(a){var b=this.m[0];if(!arguments.length)return!!b.length;b=b.indexOf(a);return-1===b?a:b};function M(a){a.K.unshift(0);a.s.unshift({})}
Ka.prototype.f=function(a,b){if(p(a)){var c=this.s[0];if(1<arguments.length&&(null===b||'number'===typeof b||'string'===typeof b||'boolean'===typeof b||'undefined'===typeof b||b instanceof Array&&0===b[0]))c[a]={O:!0,value:b};else{if(!c.hasOwnProperty(a)||c[a].N||c[a].O)c[a]={N:!1,V:this.o[0],index:this.K[0]++};return c[a].index}}};function O(){var a=N;a.s.shift();a.K.shift()};var Ma=/([.?*+^$[\]\\(){}|-])/g;function Oa(a){return'('+(a instanceof RegExp?a.toString().split('/').slice(1,-1).join('/'):String(a).replace(Ma,'\\$1'))+')'}function Pa(a,b){var c,d,e=a.type;b instanceof Array||(b=[b]);for(c=0;c<b.length;c++)if(d=b[c],e instanceof Array?-1!==e.indexOf(d):d===e)return!0}function P(){this.buffer=[];this.A='';this.w=0;this.v=null;for(var a=[],b=this.X=[],c=0;c<arguments.length;c+=2)b.push(arguments[c]),a.push(Oa(arguments[c+1]));this.G=new RegExp(a.join('|'),'g')}
P.prototype.U=function(a){var b=Array.prototype.slice.call(arguments,1);this.G.lastIndex=0;this.buffer.splice(0,Infinity);this.A=a;this.w=a.length;this.v=b.length?b:null;return this};P.prototype.h=-1;P.prototype.i=function(){function a(){this.v=c}var b=this.v,c=Array.prototype.slice.call(arguments);if(c.length){if(c=c.sort(),b&&String(b)===String(c))return this}else{if(null===b)return this;c=null}a.prototype=this;return new a};function Qa(a,b){var c=a.v;return c&&Pa(b,c)}
P.prototype.has=function(a){return'$PROP_'+String(a)in this};P.prototype.get=function(a){return this['$PROP_'+String(a)]};P.prototype.set=function(a,b){this['$PROP_'+String(a)]=1<arguments.length?b:!0;return this};
function Ra(a,b){for(var c=a.buffer,d=b-c.length+1;0<d--;){var e,f,g=a,k=g.buffer,m=g.G,l=m.lastIndex,u=g.w;if(l>=u)k.push({type:-1,D:u});else if(f=m.exec(e=g.A)){for(l<(u=f.index)&&k.push({type:-2,D:l,value:e.slice(l,u)});void 0===f.pop(););k.push({type:g.X[f.length-1],D:u,value:f[0]})}else m.lastIndex=u,k.push({type:-2,D:l,value:e.slice(l)})}return c[b]}function Sa(a,b){var c,d=0,e=a.buffer;if(b)for(;c=Ra(a,0),e.shift(),Qa(a,c););else for(;c=Ra(a,d++),Qa(a,c););return c}
function Ta(a,b,c){for(var d,e=b.length,f=0,g=0,k=[];;)if(Pa(d=Ra(a,g++),b[f])){if(k.push(d),++f>=e)break}else if(!Qa(a,d))return;if(!c)return!0;for(a=a.buffer;g--;)a.shift();return 1===k.length?k[0]:k}function Ua(a){var b=a.buffer;return b.length?b[0].D:a.G.lastIndex}function Va(a,b){var c=a.w;a.buffer.splice(0,Infinity);a.G.lastIndex=b>=c?c:b;return a}function Wa(a){var b=Ua(a),c=b>=a.w?-1:a.A[b];return Va(a,b+1),c}P.prototype.a=function(){return arguments.length?Ta(this,arguments,!0):Sa(this,!0)};
P.prototype.b=function(){return arguments.length?Ta(this,arguments,!1):Sa(this,!1)};function Xa(a){for(var b=-1,c=1,d=a.A,e=Ua(a);++b<e;)a=d.charCodeAt(b),10!==a&&13!==a||c++;return c};function Ya(a){var b,c,d=a.length-1;for(a.push(a.shift());d--;)switch(c=a.shift(),q(c)?c[0]:null){case 24:for(b=1;b<c.length;b+=2)Ya(c[b]);a.push(c);break;case 39:Ya(c[1]);a.push(c);break;case 25:for(b=3;b<c.length;b+=2)Ya(c[b]);a.push(c);break;case 23:case 27:case 33:a.push(c)}}function Za(a,b){var c=a[b];if(q(c))switch(c[0]){case 37:case 27:case 38:Za(c,1);a.splice(b+1);27===c[0]&&Ya(a);break;default:for(var d=1;d<c.length;d++)Za(c,d)}}
function $a(a){function b(){return++e+'$removeUnusedVars'}function c(a){function c(a){if(q(a))switch(a[0]){case 23:c(a[1]);d[0][a[2]]=a;break;case 21:e.push(d[a[1]][a[2]]);break;case 24:for(var f=1;f<a.length;f+=2)c(a[f+1]),d.unshift({}),c(a[f]),d.shift();break;case 28:d.unshift({});for(f=1;f<a.length;f++)c(a[f]);d.shift();break;case 39:d.unshift({});c(a[1]);d.shift();c(a[2]);break;case 25:d.unshift({});var f=b(),g=b();a[1]&&(d[0][a[1]]=f);a[2]&&(d[0][a[2]]=g);c(a[3]);-1===e.indexOf(f)&&(a[1]=null);
-1===e.indexOf(g)&&(a[2]=null);d.shift();c(a[4]);for(f=5;f<a.length;f+=2)c(a[f+1]),d.unshift({}),c(a[f]),d.shift();break;case 26:g=[];d.unshift({});for(f=4;f<a.length;f+=2)g.push(f,d[0][a[f]+1]=b());c(a[2]);for(d.shift();g.length;)-1===e.indexOf(g.pop())?a.splice(g.pop(),2):c(a[g.pop()+1]);break;default:for(f=1;f<a.length;f++)c(a[f])}}var d=[{}],e=[];return c(a),e}function d(a,b){if(!q(a))return!1;var c,e=!1,f=a.length;for(a.push(a.shift());--f;)switch(q(c=a.shift())?c[0]:null){case 23:-1!==b.indexOf(c)?
(e=d(c[1],b)||e,a.push(c)):e=!0;break;default:e=d(c,b)||e,a.push(c)}return e}for(var e=0;d(a,c(a)););}
function ab(a){function b(a,d){if(q(a))switch(a[0]){case 27:return!d;case 37:case 38:case 23:case 33:return!0;case 28:for(var c=1;c<a.length;c++)if(!b(a[c],!0))return!1;return!0;case 29:for(c=1;c<a.length;c++)if(!b(a[c],d))return!1;return!0;case 24:for(c=1;c<a.length;c+=2)if(!b(a[c],d))return!1;return!0;case 25:for(c=3;c<a.length;c+=2)if(!b(a[c],d))return!1;return!0;case 39:return b(a[1],d)}return!1}return function(a){if(q(a)){var c=a.length;if(-1!==[28,29].indexOf(a[0])){var e,f=0;for(a.push(a.shift());--c;)e=
ab(a.shift()),b(e)?f?a.splice(a.length-f,0,e):a.push(e):null===e||'undefined'===typeof e||'boolean'===typeof e||'string'===typeof e||'number'===typeof e?(e=J(e),f?a[a.length-f]+=e:(f++,a.push(e))):q(e)&&0===e[0]?(e=J(void 0),f?a[a.length-f]+=e:(f++,a.push(e))):(f=0,a.push(e));2===a.length&&p(a[1])&&(a=a[1])}else for(e=1;e<c;e++)a[e]=ab(a[e])}return a}(a)}function bb(a){Za([a],0);$a(a);return ab(a)};var N,cb,db=/^[1-9][0-9]*$/,eb=/\\(x[0-9A-F]{2}|u[0-9A-F]{4}|\n|.)/g;function fb(a){return'label "'+a+'" has already been declared'}function gb(a,b){var c=N.baseURI,d=Xa(a);return{baseURI:c,lineNumber:d,toString:function(){return this.message},message:c+'('+d+') Syntax error: '+b}}function Q(a,b){b||(b=a.b(),b='unexpected '+(b.type===a.h?'EOF':'"'+b.value+'"'));throw new gb(a,b);}
function hb(a){return a.replace(eb,function(a,c){switch(c[0]){case '0':return String.fromCharCode(0);case 'b':return String.fromCharCode(8);case 'f':return String.fromCharCode(12);case 'n':return String.fromCharCode(10);case 'r':return String.fromCharCode(13);case 't':return String.fromCharCode(9);case 'v':return String.fromCharCode(11);case 'x':return String.fromCharCode(parseInt(c.substr(1),16));case 'u':return String.fromCharCode(parseInt(c.substr(1),16));default:return c}})}
function ib(a){var b=[];do b.push(R(a));while(a.a(20));return b}function jb(a){var b=[];a.a(25)&&!a.a(26)&&(b=ib(a),a.a(26)||Q(a));return b}function kb(a,b){var c,d=[];if(b&&(c=a.a(8)))d.push(c.value,null);else if(a.a(25)&&!a.a(26)){do(c=a.a(8))?(-1!==d.indexOf(c=c.value)&&Q(a,'duplicate parameter name "'+c+'"'),d.push(c,a.a(30)?[d.length/2,R(a)]:null)):Q(a);while(a.a(20));a.a(26)||Q(a)}return d}
function lb(a,b){var c=a.a();switch(c.type){case 41:for(;!a.b([a.h,42]);)a.a();c=a.a(42)?[-1]:Q(a);break;case 70:c=mb(a);break;case 39:var c=a.i(7),d;if(c.a(51)){d=c;var e=[24];do e.push(R(d)),d.a(40)||Q(d),M(N),e.push(S(d),e.pop()),O();while(d.a(47));d.a(50)&&(d.a(40)||Q(d),M(N),e.push(S(d)),O());d=d.a(34,51,40)?e:Q(d)}else if(c.a(53)){d=c;c=[25,null,null,null,null];if(e=d.a(8))e=e.value,d.a(19)?(c[1]=e,c[2]=(d.a(8)||Q(d)).value,c[1]===c[2]&&Q(d,'key and value must differ')):c[2]=e;d.a(52)||Q(d);
c[4]=R(d);d.a(68)?(e=(d.a(8)||Q(d)).value,h(N.C(e))&&Q(d,fb(e))):e=null;d.a(40)||Q(d);M(N);N.B(e);N.f('self');c[1]=N.f(c[1]);c[2]=N.f(c[2]);c[3]=S(d);N.m.shift();for(O();d.a(47);)e=R(d),d.a(40)||Q(d),M(N),c.push(S(d),e),O();d.a(50)&&(d.a(40)||Q(d),M(N),c.push(S(d)),O());d=d.a(34,53,40)?c:Q(d)}else if(c.a(54)){d=c;var f=[-3];if(d.b(8,[62,25,30])){do e=N.f((d.a(8)||Q(d)).value,c=d.a(30)?R(d):d.b([62,25])?nb(d):Q(d)),0<=e&&f.push([23,c,e]);while(d.a(20))}else e=(d.a(8)||Q(d)).value,d.a(40)||Q(d),e=N.f(e,
c=ob(d)),0<=e&&(f=[23,c,e]),d.a(34,54)||Q(d);d=d.a(40)?f:Q(d)}else if(c.a(69))d=c,c=[39,null],d.b([40,68])||c.push(R(d)),d.a(68)&&(e=(d.a(8)||Q(d)).value,h(N.C(e))&&Q(d,fb(e))),d.a(40)||Q(d),M(N),N.B(e),N.f('self'),c[1]=S(d),N.m.shift(),O(),d=d.a(34,69,40)?c:Q(d);else if(c.a(49)){var e=c,c=(e.a(8)||Q(e)).value,f=[26,null,null],g=kb(e);e.a(40)||Q(e);M(N);La(f);N.B();N.f('self');if(g.length)for(f.push(g.length/2);g.length;)N.f(g.shift()),(d=g.shift())&&Array.prototype.push.apply(f,d);f[2]=S(e);N.o.splice(0,
2);N.m.shift();O();f[1]=pb(f[2]);d=e.a(34,49,40)?[23,f,N.f(c)]:Q(e)}else c.a(48)?(d=c,e=[27],d.a(40)?(e.push(ob(d)),d.a(34,48)||Q(d)):e.push(R(d)),d=d.a(40)?e:Q(d)):c.a(66)?d=qb(c,37):c.a(67)?d=qb(c,38):c.a(59)?(d=c,e=[33,R(d)],d=d.a(40)?e:Q(d)):c.b(34,2,40)?d=[-2]:c.b(2)?d=[-2]:(d=c,d.a(40)?d=[-1]:(e=R(d),d=d.a(40)?e:Q(d)));c=d;break;case 43:c=rb(a);break;case a.h:c=[-2];break;default:c=c.value}switch(q(c)?c[0]:null){case -1:return!0;case -2:return!1;case -3:return Array.prototype.push.apply(b,c.slice(1)),
!0;default:return b.push(c),!0}}function pb(a){function b(a){if(q(a))switch(a[0]){case 21:if(3<a.length){var e=a.slice(2).join('.');-1===c.indexOf(e)&&(c.push(e),d.push([a[0],a[3],a[2]]));a.splice(3)}break;case 26:break;default:for(e=1;e<a.length;e++)b(a[e])}}var c=[],d=[];b(a);return d.length?d:0}
function sb(a){var b;if(a.a(17))b=h(a=sb(a))?-a:[14,a];else{if(a.a(32))a=[5,sb(a)];else if(a.a(65))a=[36,sb(a)];else a:{if(a.a(10))b=null;else if(a.a(11))b=!0;else if(a.a(12))b=!1;else if(a.a(34))b:for(var c,d='',e=!1;;){c=Wa(a);if(!e&&'/'===c)try{c=a.i().a(1);RegExp(d,c=c?c.value:'');d=[2,d];c&&d.push(c);b=d;break b}catch(k){Q(a,k.message)}'\\'===c?(d+='\\',c=Wa(a)):'['===c?e=!0:']'===c&&(e=!1);-1!==[a.h,'\n','\r'].indexOf(c)&&Q(a,'unterminated regexp literal "'+d+'"');d+=c}else if(a.a(70))b=mb(a);
else if(a.a(0))b=[0];else if(a.a(43))b=rb(a);else if(a.a(27)){var d=0,e={},f=[1];do{for(;a.a(20););if(a.b(28))break;(b=a.a(1,19))?(b=b[0].value,c=R(a)):(p(b=R(a))||h(b))&&a.a(19)?(c=R(a),p(b)&&db.test(b)&&(b=parseInt(b,10)),h(b)&&(b=Math.floor(b),b<d?b=String(b):(d=b,b=String(d++)))):(c=b,b=String(d++));e.hasOwnProperty(b)?f[e[b]]=c:(e[b]=f.length,f.push(c,b))}while(a.a(20));a.a(28)||Q(a);b=f}else if(a.a(39))b=ob(a,!0);else if(a.a(45))b=[3];else if(a.a(46))b=[4];else if(a.b([36,35]))b:{b=a;d='';e=
b.a().value;for(b=b.i();c=b.a();)if(c.type===b.h)Q(b,'unterminated string literal '+(e+d+e));else{if((c=c.value)===e){b=hb(d);break b}d='\\'===c?d+('\\'+b.a().value):d+c}b=void 0}else if(a.b(5))b=parseInt(a.a().value,10);else if(a.b(58))b=parseInt(a.a().value.slice(2),2);else if(a.b(3))b=parseInt(a.a().value.slice(2),16);else if(a.b(4))b=parseFloat(a.a().value);else if(a.b(6)){b=a.a().value;b:{d=N;c=d.o;for(var g=d.s,e=g.length,d=0;d<e;d++)if(f=g[d],f.hasOwnProperty(b)){f=f[b];if(f.O){c=f.value;break b}if(c[0]===
f.V){c=[21,d,f.index];break b}f.N=!0;c=[21,d,f.index,d-(e-c[1])];break b}c=void 0}b=c||[].concat(22,b,jb(a),[[4]])}else a.a(25)?(b=Ua(a),c=R(a),b=a.b(20)?nb(Va(a,b-1)):a.a(26)?a.b(62)?nb(Va(a,b-1)):c:Q(a)):b=Q(a);for(;;)if(a.a(15))b=[22,0,(a.a(1)||Q(a)).value,b];else if(a.a(27))b=[22,0].concat(ib(a),[b]),a.a(28)||Q(a);else if(a.a(38))b=[22,(a.a(1)||Q(a)).value].concat(jb(a),[b]);else if(a.b(25))b=[22,1].concat(jb(a),[b]);else{a=b;break a}}b=a}return b}
function tb(a){for(var b=sb(a);a.a(13)&&(b=[11,b])||a.a(34)&&(b=[12,b])||a.a(31)&&(b=[13,b]);b.push(sb(a)));return b}function ub(a){for(var b=tb(a);a.a(14)&&(b=[9,b])||a.a(17)&&(b=[10,b]);b.push(tb(a)));return b}function vb(a){for(var b=ub(a);a.a(63)&&(b=[34,b])||a.a(64)&&(b=[35,b]);b.push(ub(a)));return b}function wb(a){for(var b=vb(a);a.a(23)&&(b=[17,b])||a.a(24)&&(b=[18,b])||a.a(22)&&(b=[15,b])||a.a(21)&&(b=[16,b]);b.push(vb(a)));return b}
function xb(a){for(var b=wb(a);a.a(30)&&(b=[19,b])||a.a(29)&&(b=[20,b]);b.push(wb(a)));return b}function yb(a){for(var b=xb(a);a.a(57)&&(b=[32,b]);b.push(xb(a)));return b}function zb(a){for(var b=yb(a);a.a(56)&&(b=[31,b]);b.push(yb(a)));return b}function Ab(a){for(var b=zb(a);a.a(55)&&(b=[30,b]);b.push(zb(a)));return b}function Bb(a){for(var b=Ab(a);a.a(16)&&(b=[6,b]);b.push(Ab(a)));return b}
function nb(a){var b,c=[29],d=[26,null,c],e=kb(a,!0);a.a(62)||Q(a);M(N);La(d);N.f('self');if(e.length)for(d.push(e.length/2);e.length;)N.f(e.shift()),(b=e.shift())&&Array.prototype.push.apply(d,b);c.push([27,R(a)]);N.o.splice(0,2);O();d[1]=pb(c);return d}
function R(a){if(a.b(62)||a.b(8,62)||a.b(25,26)||a.b(25,8,20)||a.b(25,8,26,62))a=nb(a);else{var b;for(b=Bb(a);a.a(18)&&(b=[7,b]);b.push(Bb(a)));for(;a.a(33)&&(b=[8,b,R(a)]);a.a(19)&&b.push(R(a)));q(b)&&8===b[0]&&q(b[1])&&5===b[1][0]&&(b[1]=b[1][1],3===b.length&&b.push([0]),b[3]=[b[2],b[2]=b[3]][0]);a=b}return a}
function qb(a,b){N.C()||Q(a,37===b?'illegal break statement':'illegal continue statement');var c;a.b(40)||((c=a.a(8))||Q(a),p(c=N.C(c.value))&&Q(a,'undefined label "'+c+'"'));return a.a(40)?c?[b,c]:[b]:Q(a)}function rb(a){var b='';for(a=a.i();!a.b([a.h,44]);)b+=a.a().value;return a.a(44)?b:Q(a)}function mb(a){var b=N;a=a.i();var c=[29];for(N=new Ka(N.baseURI);!a.b([a.h,71])&&lb(a,c););a.a(71)||Q(a);c=bb(c);N=b;return JSON.stringify(c)}
function ob(a,b){a=a.i();var c=[28];M(N);for(N.B();(!b||!a.b(40))&&lb(a,c););N.m.shift();O();return!b||a.a(40)?ab(c):Q(a)}function S(a){a=a.i();for(var b=[29];lb(a,b););return ab(b)};var Cb=/^\s*\[\s*[0-9]+.*\]\s*$/;
function Db(a,b){var c=(cb||(cb=new P([1,0],/undefined\b/,[1,10],/null\b/,[1,11],/true\b/,[1,12],/false\b/,[1,2,47],/elseif\b/,[1,2,51],/if\b/,[1,2,52],/in\b/,[1,2,68],/as\b/,[1,2,53],/for\b/,[1,2,54],/var\b/,[1,2,50],/else\b/,[1,2,49],/macro\b/,[1,2,48],/return\b/,[1,2,66],/break\b/,[1,2,67],/continue\b/,[1,2,69],/while\b/,58,/0[bB][0-1]+/,3,/0[xX][0-9A-Fa-f]+/,4,/(?:[0-9]*\.)?[0-9]+[eE][+-]?[0-9]+/,4,/[0-9]*\.[0-9]+/,5,/[0-9]+/,[1,6,45],/this\b/,[1,6],/self\b/,[1,6,46],/global\b/,[1,6,8],/[_$a-zA-Z][_$a-zA-Z0-9]*/,
7,/[\x0A\x0D\x09\x20]+/,43,'{{%',44,'%}}',70,'{{#',71,'#}}',41,'{{*',42,'*}}',40,'}}',39,'{{',38,'->',62,'=>',29,'!=',18,'||',16,'&&',65,'~',63,'<<',64,'>>',56,'^',55,'|',57,'&',32,'!',59,'@',35,'"',36,"'",30,'=',31,'%',19,':',20,',',33,'?',23,'<=',24,'>=',22,'<',21,'>',15,'.',17,'-',14,'+',13,'*',34,'/',25,'(',26,')',27,'[',28,']'))).U(a);N=new Ka(b);a=S(c);return c.b(c.h)?bb(a):Q(c)}
function Eb(a,b){if(p(a)){if(Cb.test(a))try{return JSON.parse(a)}catch(c){}if(Db)return Db(a,b)}return q(a)?a:[0]};function Fb(a,b){this.result='';this.level=a;this.S=b}Fb.prototype.extend=function(a){this.result=a+this.result;return this};function Hb(a,b,c){var d,e=new B,f=0;n(function(g,k){g?A(a[k],b,d||(d=function(b,d){f|=d;if(d&2)return c(b,f);e.set(b,a[g.g+1]);g()})):c(e,f)},1,a.length-1,2)}function Ib(a,b,c){A(a[1],b,function(d,e){if(e&2)return c(d,e);var f=I(d);switch(a[0]){case 5:c(!f,e);break;case 6:f=!f;default:f?c(d,e):A(a[2],b,function(a,b){c(a,e|b)})}})}
function Jb(a,b,c){A(a[1],b,function(d,e){if(e&2)return c(d,e);I(d)?A(a[2],b,function(a,b){c(a,e|b)}):3<a.length?A(a[3],b,function(a,b){c(a,e|b)}):c(void 0,e)})}function Kb(a,b,c){A(a[1],b,function(a,b){if(b&2)return c(a,b);a=K(a);c(a&&-a,b)})}
function Lb(a,b,c){A(a[1],b,function(d,e){if(e&2)return c(d,e);d=h(d=K(d))?d|0:0;36===a[0]?c(~d,e):A(a[2],b,function(b,g){e|=g;if(g&2)return c(b,e);b=h(b=K(b))?b|0:0;switch(a[0]){case 30:d|=b;break;case 31:d^=b;break;case 32:d&=b;break;case 34:d<<=b;break;case 35:d>>=b}c(d,e)})})}
function Mb(a,b,c){A(a[1],b,function(d,e){if(e&2)return c(d,e);A(a[2],b,function(b,g){e|=g;if(g&2)return c(b,e);p(d)&&h(b)?p(d=K(d,d))&&(b=J(b)):h(d)&&p(b)?p(b=K(b,b))&&(d=J(d)):d instanceof D&&b instanceof D&&(d=d.toJavaScript().getTime(),b=b.toJavaScript().getTime());h(d)&&h(b)||(p(d)&&p(b)?-1===[19,20].indexOf(a[0])&&(d=d.length,b=b.length):(d=I(d),b=I(b)));switch(a[0]){case 19:d=d===b;break;case 20:d=d!==b;break;case 15:d=d<b;break;case 16:d=d>b;break;case 17:d=d<=b;break;case 18:d=d>=b}c(d,e)})})}
function Nb(a,b,c){A(a[1],b,function(d,e){if(e&2)return c(d,e);void 0===(d=K(d))?c(void 0,e):A(a[2],b,function(b,g){e|=g;if(g&2)return c(b,e);if(void 0===(b=K(b)))d=void 0;else switch(a[0]){case 10:d-=b;break;case 11:d*=b;break;case 12:d/=b;break;case 13:d%=b}c(h(d)?d:void 0,e)})})}
function Ob(a,b,c){A(a[1],b,function(d,e){if(e&2)return c(d,e);A(a[2],b,function(a,b){e|=b;if(b&2)return c(a,e);a:{if(!p(d)&&!p(a)){if(d instanceof B&&a instanceof B){d=d.concat(a);break a}var f=K(d),g=K(a);if(h(f)){d=h(g)?f+g:void 0;break a}if(h(g)){d=h(f)?f+g:void 0;break a}}d=J(d)+J(a)}c(d,e)})})}function Pb(a,b,c){var d,e=[],f=0;n(function(g,k){g?A(a[k],b,d||(d=function(a,b){f|=b;if(b&2)return c(a,f);e.push(a);g()})):Ca(e.pop(),a[1],e,function(a,b){c(a,f|b)},b)},2,a.length-1)}
function Qb(a,b,c){var d=a[1],d=(d?b.L[d-1]:b).T[a[2]];if(!c)return d[1];c(d[0],d[1])}function Rb(a,b,c){A(a[1],b,function(d,e){if(e&2)return c(d,e);23===a[0]&&z(b,d,a[2],!0,e);c('',e)})}function Sb(a,b,c){var d,e,f;if(q(e=a[1])){for(f=0;e.length&&!(f|=Qb(e.shift(),b),f&1););a[1]=f}else f=e;e=Array(a[3]||0);n(function(g,k){g?A(a[k+1],b,d||(d=function(b,d){f|=d;if(f&2)return c(b,f);e[a[g.g]]=b;g()})):c(new y(e,a[2],b),f)},4,a.length-1,2)}
function Tb(a,b,c,d,e){function f(a,b){d(a,l|b)}function g(a,b){c(a,l|b)}var k,m=a.length-1,l=0;n(function(e,x){e?x===m?A(a[x],b.extend(),g,f):A(a[x+1],b,k||(k=function(c,k){l|=k;if(l&2)return d(c,l);I(c)?A(a[e.g],b.extend(),g,f):e()})):c('',l)},e,m,2)}function Ub(a,b,c,d){function e(a,b){d(a,k|b)}var f,g='',k=0;n(function(m,l){m?A(a[l],b,f||(f=function(a,b){k|=b;b&2?d(a,k):a instanceof Fb?c(a.extend(g),k):(g+=J(a),m())}),e):c(g,k)},1,a.length-1)}
function Vb(a,b,c,d){var e,f,g,k=a[1],m='',l=0,u=2<a.length?a[2]:!0;n(function(a){A(u,b,g||(g=function(g,x){l|=x;if(x&2)return d(g,l);I(g)?(e=b.extend(),z(e,{iteration:a.g,condition:g},0,!1),A(k,e,f||(f=function(b,e){l|=e;if(e&2)return d(b,l);b instanceof Fb?b.extend(m).level?(b.level--,c(b,l)):b.S?a():c(b.result,l):(m+=b,a())}),d)):c(m,l)}),d)})}
function Wb(a,b,c,d){A(a[4],b,function(e,f){if(f&2)return d(e,f);if(e instanceof B&&e.getLength()){var g,k,m='',l=a[1],u=a[2],x=a[3];wa(e,function(a,e,Gb,uc,wc){a?(g=b.extend(),z(g,{key:Gb,value:e,index:uc,last:wc},0,!1),l&&z(g,Gb,l,!0),u&&z(g,e,u,!0),A(x,g,k||(k=function(b,e){f|=e;if(e&2)return d(b,f);b instanceof Fb?b.extend(m).level?(b.level--,c(b,f)):b.S?a():c(b.result,f):(m+=b,a())}),d)):c(m,f)})}else Tb(a,b,function(a,b){f|=b;if(b&2)return d(a,f);c(a,f)},function(a,b){f|=b;if(b&2)return d(a,
f);d(a,f)},5)})}
function A(a,b,c,d){if(q(a))switch(a[0]){case 0:c(void 0,0);break;case 3:c(b.R,1);break;case 4:c(Fa,0);break;case 2:c(new RegExp(a[1],a[2]||''),0);break;case 1:Hb(a,b,c);break;case 14:Kb(a,b,c);break;case 9:Ob(a,b,c);break;case 22:case 40:Pb(a,b,c);break;case 8:Jb(a,b,c);break;case 26:Sb(a,b,c);break;case 21:Qb(a,b,c);break;case 7:case 5:case 6:Ib(a,b,c);break;case 10:case 11:case 12:case 13:Nb(a,b,c);break;case 19:case 20:case 15:case 16:case 17:case 18:Mb(a,b,c);break;case 34:case 35:case 30:case 31:case 32:case 36:Lb(a,b,
c);break;case 23:case 33:Rb(a,b,c);break;case 24:Tb(a,b,c,d||c,1);break;case 29:Ub(a,b,c,d||c);break;case 28:Ub(a,b.extend(),c,c);break;case 25:Wb(a,b,c,d||c);break;case 39:Vb(a,b,c,d||c);break;case 27:A(a[1],b,d||c);break;case 37:case 38:c(new Fb(a[1],38===a[0]),0);break;default:throw'UNKNWON_NODE_TYPE: '+a[0];}else c(a,0)}function T(a,b,c){this.L=[];this.T={};this.baseURI=a;this.M=c;this.R=G(b)}T.prototype=Object.create(ta.prototype);T.prototype.constructor=T;
function z(a,b,c,d,e){d||(b=G(b));h(e)&&0<=e||(e=0);a.T[c]=[b,e]}T.prototype.extend=function(){var a=new T(this.baseURI,this.R,this.M);a.L=[this].concat(this.L);return a};T.prototype.getBaseURI=function(){return this.baseURI};function Xb(a,b,c){A(b,a,c)};var Yb=null,Zb={},$b={},ac=!0;function bc(a,b,c,d){var e,f=[];d?f=Zb.hasOwnProperty(a)?Zb[a]:Zb[a]=[]:Zb.hasOwnProperty(a)&&delete Zb[a];n(function(g){e||(e=[function(){f=Array.prototype.slice.call(arguments);d&&(Zb[a]=f);g()},c]);b.apply(null,e.concat(f))})}function cc(a,b){return(a instanceof t?1:a instanceof T?2:3)-(b instanceof t?1:b instanceof T?2:3)}function dc(a){return a instanceof B&&a.has('cache')&&!I(a.get('cache'))}
function ec(a,b){a=ha(a);var c=a.query,d=new B;'string'===typeof c&&c.replace(/([^?=&]+)(=([^&]*))?/g,function(a,b,c,k){d.set(k||'',b)});b instanceof B||(b=[new B,J(b)],b[1]&&b[0].set('',b[1]),b=b[0]);a.query=d.concat(b).map(function(a,b){return b+'='+encodeURIComponent(a)}).getValues().join('&');return(a.scheme?a.scheme+'://':'')+(a.u?a.u:'')+(a.path?a.path:'')+(a.query?'?'+a.query:'')+(a.J?'#'+a.J:'')}
function fc(a,b,c,d){c={method:'GET',cache:!c};if(b instanceof B){if(b.has('method')){var e=J(b.get('method')).toUpperCase();c.method=-1===['GET','POST'].indexOf(e)?'GET':e}b.has('data')&&('POST'===c.method?c.data=Ea(b.get('data')):a=ec(a,b.get('data')))}d(a,c)}function gc(a,b,c,d){r(Yb)?fc(a,d,c,function(a,c){Yb(a,b,c)}):b()}
function hc(a,b){if(r(b)){if(!p(a))return b();var c,d,e=Array.prototype.slice.call(arguments,2).sort(cc);e[0]instanceof t&&e.shift();if(e[0]instanceof T&&(d=e.shift(),a=ia(a,d.baseURI),!p(a)))return b();e.length&&(c=G(e.shift()));var f=dc(c);ic([0,a],function(b,d,e,l){l?d(e,f?1:0):gc(a,function(a){b(p(a)?a:void 0,!0)},f,c)},b,f)}}
function jc(a,b){if(r(b)){if(!p(a))return b();var c,d,e=qa,f=Array.prototype.slice.call(arguments,2).sort(cc);f[0]instanceof t&&(e=f.shift());if(f[0]instanceof T&&(d=f.shift(),a=ia(a,d.baseURI),!p(a)))return b();f.length&&(c=G(f.shift()));var g=dc(c);ic([1,a],function(b,d,e,f){f?d(e,g?1:0):gc(a,function(a){if(p(a))try{a=a.replace(/^\s*([$A-Z_][0-9A-Z_$]*)?\s*\(\s*/i,''),a=a.replace(/\s*\)\s*(;\s*)*\s*$/,''),a=JSON.parse(a)}catch(Na){a=void 0}b(G(a),!0)},g,c)},function(a,c){e===pa&&(a=Ea(a));b(a,c)},
g)}}function ic(a,b,c,d){var e=ac&&!d;if($b.hasOwnProperty(a=JSON.stringify(a)))$b[a].push(b,c,e);else{var f=$b[a]=[b,c,e];n(function(d){f.length?(b=f.shift(),c=f.shift(),e=f.shift(),bc(a,b,function(){c.apply(this,arguments);d()},e)):delete $b[a]})}}
function kc(a,b){if(r(b)){if(!p(a))return b();var c,d,e=qa,f=Array.prototype.slice.call(arguments,2).sort(cc);f[0]instanceof t&&(e=f.shift());if(f[0]instanceof T&&(d=f.shift(),a=ia(a,d.baseURI),!p(a)))return b();f.length&&(c=G(f.shift()));ic([2,a],function(b,e,f,l,u){switch(f){case 2:e(l,u);break;case 1:Xb(new T(a,c,d?d.M:void 0),l,function(a,c){c&1?e(a,c):b(2,a,c)});break;default:gc(a,function(c){c=p(c)?Eb(c,a):void 0;b(1,c)})}},function(a,c){e===pa?a=Ea(a):e===ra&&(a=J(a));b(a,c)})}};function lc(a,b){this.baseURI=b;this.P=a}lc.prototype.getBaseURI=function(){return this.baseURI};lc.prototype.getAST=function(){return this.P};function mc(a,b){return(a instanceof t?1:a instanceof Function?2:3)-(b instanceof t?1:b instanceof Function?2:3)}
lc.prototype.render=function(){var a,b=qa,c=Array.prototype.slice.call(arguments).sort(mc);c[0]instanceof t&&(b=c.shift());c[0]instanceof Function&&(a=c.shift());Xb(new T(this.baseURI,c[0],c[1]),this.P,function(c){b===pa?c=Ea(c):b===ra&&(c=J(c));a?(a(c),a=void 0):a=c});return a};var nc=w.prototype,oc=/^[_$a-zA-Z][_$a-zA-Z0-9]*$/;H(nc,'toJSON','null');H(nc,2,sa);H(nc,'hasMethod',function(a,b){var c=b[0];return p(c)&&oc.test(c)&&Ba(a,c,!0)});H(nc,'getMethod',function(a,b,c){var d=b.shift();if(p(d)&&oc.test(d)&&Ba(a,d,!0))return new y([],function(b){return[22,d].concat(b,a)},c)});var pc=ua.prototype;H(w.prototype,'isUndefined',!1);H(pc,'isUndefined',!0);var qc=va.prototype;H(w.prototype,'isNull',!1);H(qc,'isNull',!0);H(qc,'toBoolean',!1);H(qc,'toString','null');H(qc,'toJSON','null');var rc=w.prototype,sc=Ga.prototype;H(rc,'isBoolean',!1);H(rc,'toBoolean',!1);H(sc,'isBoolean',!0);H(sc,'toBoolean',sa);H(sc,'toNumber',function(a){return a?1:0});H(sc,'toString',function(a){return a?'true':'false'});H(sc,'toJSON',function(a){return a?'true':'false'});var U=Ha.prototype;H(w.prototype,'isNumber',!1);H(U,'isNumber',!0);H(U,'toNumber',sa);H(U,'isInt',function(a){return 0===a%1});H(U,'isFloat',function(a){return 0!==a%1});H(U,'toBoolean',function(a){return!!a});H(U,'toJSON',function(a){return JSON.stringify(a)});H(U,'toAbs',function(a){return Math.abs(a)});H(U,'toFloor',function(a){return Math.floor(a)});H(U,'toCeil',function(a){return Math.ceil(a)});H(U,'toRound',function(a){return Math.round(a)});H(U,'toChar',function(a){if(0===a%1&&0<=a)return String.fromCharCode(a)});
H(U,'toFixed',function(a,b){var c=L(b[0],0);void 0===c&&(c=0);try{a=parseFloat(a.toFixed(c))}finally{return a}});H(U,'toString',function(a){var b=String(a).split(/[eE]/);if(1===b.length)return b[0];var c='',d=b[0].replace('.',''),b=Number(b[1])+1;if(0>b){0>a&&(c+='-');for(c+='0.';b++;)c+='0';return c+d.replace(/^\-/,'')}for(b-=d.length;b--;)c+='0';return d+c});var tc=w.prototype,V=Ia.prototype;H(tc,'isString',!1);H(tc,'toString','');H(V,0,function(a,b){var c=L(b[0]);if(void 0!==c){var d=a.length;0>c&&(c=d+c);if(0<=c&&c<d)return a[c]}});H(V,'isString',!0);H(V,'toString',sa);H(V,'toNumber',function(a){return ga(a)});H(V,'toBoolean',function(a){return 0<a.length});H(V,'toJSON',function(a){return JSON.stringify(a)});H(V,'length',function(a){return a.length});H(V,'toLowerCase',function(a){return a.toLowerCase()});H(V,'toUpperCase',function(a){return a.toUpperCase()});
H(V,'htmlentities',function(a){return ja(a)});H(V,'split',function(a,b){var c=b[0];p(c)&&(c=c.replace(ca,'\\$1'),c=new RegExp(c,'g'));return a.split(c instanceof RegExp?c:'')});H(V,'charCodeAt',function(a,b){var c=L(b[0]);if(void 0!==c){var d=a.length;0>c&&(c=d+c);if(0<=c&&c<d)return a.charCodeAt(c)}});
H(V,'strip',function(a,b){for(var c,d='',e=-1,f=a.length;b.length;)p(c=b.shift())&&(d+=c);for(0===d.length&&(d=' \n\r\t');e<f&&-1!==d.indexOf(a.charAt(++e)););for(;0<=f&&-1!==d.indexOf(a.charAt(--f)););return a.slice(e,f+1)});H(V,'slice',function(a,b){var c=a.length,d=0<b.length?L(b[0]):0,e=1<b.length?L(b[1]):c;if(void 0!==d&&void 0!==e){0>d&&(d=c+d);0>d&&(d=0);if(d>=c)return'';0===e&&(e=c-d);0>e&&(e=c-d+e);return 0>=e?'':a.substr(d,e)}});
H(V,'replace',function(a,b,c,d){var e=b[0],f=b[1];p(e)&&(e=new RegExp(e.replace(ca,'\\$1'),'g'));if(e instanceof RegExp)if(f instanceof y){var g,k,m='',l=0,u=0;n(function(b){(g=e.exec(a))?(l<g.index&&(m+=a.slice(l,g.index)),l=g.index+g[0].length,f.call(Array.prototype.slice.call(g),c,k||(k=function(a,c){u|=c;m+=a;b()}))):d(m+a.slice(l),u)})}else d(a.replace(e,J(f)));else d(a)});var vc=Ja.prototype;H(w.prototype,'isRegExp',!1);H(vc,'isRegExp',!0);H(vc,'toBoolean',!0);H(vc,'toString',function(a){return String(a)});H(vc,'toJSON',function(a){return JSON.stringify(String(a))});H(vc,'test',function(a,b){return a.test(J(b[0]))});var xc=w.prototype,W=B.prototype;function yc(a){var b=a.getKeys(),c=new B;a.getValues().forEach(function(a,e){p(a)?a=ja(a):a instanceof B&&(a=yc(a));c.set(a,b[e])});return c}function zc(a,b,c){var d=a.length;if(2>d)c(a);else{var e=parseInt(d/2);zc(a.slice(0,e),b,function(f){zc(a.slice(e,d),b,function(a){Ac(f,a,b,c)})})}}
function Ac(a,b,c,d){var e,f=[];n(function(g){a.length&&b.length?c(a[0],b[0],e||(e=function(c){f.push(c?b.shift():a.shift());g()})):(Array.prototype.push.apply(f,a),Array.prototype.push.apply(f,b),d(f))})}H(xc,'isArray',!1);H(xc,'toArray',function(a){if(a instanceof B)return a;var b=new B;b.set(a);return b});H(W,0,function(a,b){return a.get(b[0])});H(W,2,function(a){return a.toJavaScript(Ea)});H(W,'isArray',!0);H(W,'toBoolean',!0);H(W,'length',function(a){return a.getLength()});H(W,'keys',function(a){return a.getKeys()});
H(W,'values',function(a){return a.getValues()});H(W,'first',function(a){return a.getFirst()});H(W,'last',function(a){return a.getLast()});H(W,'htmlentities',function(a){return yc(a)});H(W,'has',function(a,b){return a.has(J(b[0]))});H(W,'toString',function(a){var b,c=[];for(a=a.getValues();a.length;)(b=J(a.shift()))&&c.push(b);return c.join(' ')});
H(W,'toJSON',function(a){var b=0,c=[],d=!0,e=a.getKeys();a=a.getValues();for(var f=0;f<a.length;f++)c.push(Da(a[f])),d&&e[f]!==String(b++)&&(d=!1);return d?'['+c.join(',')+']':'{'+c.map(function(a,b){return JSON.stringify(e[b])+':'+a}).join(',')+'}'});
H(W,'slice',function(a,b){var c=L(b[0]),d=L(b[1]),e=I(b[2]),f=new B,g=a.getValues(),k=g.length,e=e?[]:a.getKeys();void 0===c&&(c=0);0>c&&(c=k+c);0>c&&(c=0);if(c>k)return[];void 0===d&&(d=0);0===d&&(d=k-c);0>d&&(d=k-c+d);if(0>=d)return[];g=g.slice(c,c+d);for(e=e.slice(c,c+d);g.length;)f.set(g.shift(),e.shift());return f});H(W,'chunk',function(a,b){var c=[],d=L(b[0],1),e=a.getValues(),f=a.getKeys();void 0===d&&(d=1);for(var g,k=0;k<e.length;k++)0===k%d&&c.push(g=new B),g.set(e[k],f[k]);return c});
H(W,'join',function(a,b){var c=[],d=a.getValues(),e='';for(0<b.length&&(e=J(b[0]));d.length;)c.push(J(d.shift()));return c.join(e)});H(W,'some',function(a,b,c,d){var e,f=b.shift(),g=0;f instanceof y||(f=new y([],f,c));a.some(function(d,m,l){e||(e=function(a,b){return g|=b,m(I(a))});f.call(b.concat(d,l,a),c,e)},function(a){return d(a,g)})});
H(W,'every',function(a,b,c,d){var e,f=b.shift(),g=0;f instanceof y||(f=new y([],f,c));a.every(function(d,m,l){e||(e=function(a,b){return g|=b,m(I(a))});f.call(b.concat(d,l,a),c,e)},function(a){return d(a,g)})});H(W,'filter',function(a,b,c,d){var e,f=b.shift(),g=0;f instanceof y||(f=new y([],f,c));a.filter(function(d,m,l){e||(e=function(a,b){return g|=b,m(I(a))});f.call(b.concat(d,l,a),c,e)},function(a){return d(a,g)})});
H(W,'map',function(a,b,c,d){var e,f=b.shift(),g=0;f instanceof y||(f=new y([],f,c));a.map(function(d,m,l){e||(e=function(a,b){return g|=b,m(a)});f.call(b.concat(d,l,a),c,e)},function(a){return d(a,g)})});
H(W,'sort',function(a,b,c,d){var e=b.shift(),f=a.getKeys(),g=0;e instanceof y||(e=null);zc(a.getValues().map(function(a,b){return{key:f[b],value:a}}),function(a,d,f){e?e.call(b.concat(a.value,d.value,a.key,d.key),c,function(a,b){g|=b;f(I(a))}):f(J(a.value)>J(d.value))},function(a){for(var b=new B;a.length;)e=a.shift(),b.set(e.value,e.key);d(b,g)})});
H(W,'group',function(a,b,c,d){var e=new B,f=b.shift(),g=a.getKeys(),k=a.getValues();f instanceof y||(f=new y([],f,c));var m,l=0;n(function(u,x){u?f.call(b.concat(k[x],g[x],a),c,m||(m=function(a,b){(e.has(a=J(a))?e.get(a):e.set(new B,a)).set(k[u.g]);l|=b;u()})):d(e,l)},0,k.length-1)});
H(W,'find',function(a,b,c,d){var e,f=b.shift(),g=a.getKeys(),k=a.getValues(),m=0,l=I(b.shift());f instanceof y||(f=new y([],f,c));n(function(u,x){u?f.call(b.concat(k[x],g[x],a),c,e||(e=function(a,b){m|=b;I(a)?d((l?g:k)[u.g],m):u()})):d(void 0,m)},0,g.length-1)});
H(W,'reduce',function(a,b,c,d){var e=b.shift();if(e instanceof y){var f,g=0,k=a.getKeys(),m=a.getValues(),l=0,u=b.length?b.shift():(g++,m[0]);n(function(g,Na){g?e.call(b.concat(u,m[Na],k[Na],a),c,f||(f=function(a,b){l|=b;u=a;g()})):d(u,l)},g,m.length-1)}else d(e)});var Bc=w.prototype,X=y.prototype;H(Bc,'isMacro',!1);H(Bc,'toMacro',function(a,b,c){return a instanceof y?a:new y([],a,c)});H(X,'isMacro',!0);H(X,'toBoolean',!0);H(X,'toString',function(a){return J(a.F)});H(X,'toJSON',function(a){return Da(a.F)});H(X,'bind',function(a,b){return a.bind(b)});H(X,2,function(a){return a.toJavaScript(Ea)});H(X,0,function(a,b,c,d){Ca(a.F,0,b,c,d)});H(X,1,function(a,b,c,d){a.call(b,c,d)});
H(X,'extend',function(a,b){var c=b[0],d=a.F;c instanceof B&&(d instanceof B&&(c=d.concat(c)),a=a.clone(),a.F=c);return a});H(X,'call',function(a,b,c,d){for(var e=[],f=0;f<b.length;f++){var g=b[f];g instanceof B?Array.prototype.push.apply(e,g.getValues()):e.push(g)}a.call(e,c,d)});var Cc=Ha.prototype,Dc=Ia.prototype,Ec=C.prototype,Fc=B.prototype,Gc=D.prototype;H(w.prototype,'isDate',!1);H(Cc,'toDate',function(a,b){var c=new Date(Math.trunc?Math.trunc(a):0>a?Math.ceil(a):Math.floor(a));if(isFinite(c.getTime()))return new D(c,b[0])});
H(Dc,'toDate',function(a,b){var c=b.shift();if(p(c)){var d=[],c=new RegExp('^'+c.replace(/([YMDhms])|.+?/g,function(a,b){return b?(d.push(b),'(\\d{1,4})'):a.replace(ca,'\\$1')})+'$');if(c=a.match(c)){for(var e=new B;d.length;)switch(d.pop()){case 's':e.set(parseInt(c.pop(),10),'second');break;case 'm':e.set(parseInt(c.pop(),10),'minute');break;case 'h':e.set(parseInt(c.pop(),10),'hour');break;case 'Y':e.set(parseInt(c.pop(),10),'year');break;case 'M':e.set(parseInt(c.pop(),10),'month');break;case 'D':e.set(parseInt(c.pop(),
10),'day')}return Ca(e,'toDate',b)}}});
H(Fc,'toDate',function(a,b){var c,d=new Date(0,0,1,0,0,0);if(!a.has('year'))return;c=L(a.get('year'));if(void 0===c)return;d.setFullYear(c);if(a.has('month')){c=L(a.get('month'),1,12);if(void 0===c)return;d.setMonth(c-1);if(a.has('day')){c=ka(d.getFullYear(),d.getMonth()+1);c=L(a.get('day'),1,c);if(void 0===c)return;d.setDate(c);if(a.has('hour')){c=L(a.get('hour'),0,23);if(void 0===c)return;d.setHours(c);if(a.has('minute')){c=L(a.get('minute'),0,59);if(void 0===c)return;d.setMinutes(c);if(a.has('second')){c=
L(a.get('second'),0,59);if(void 0===c)return;d.setSeconds(c)}}}}}if(isFinite(d.getTime()))return new D(d,b[0])});H(Ec,'getDate',function(a,b){return new D(b[0])},1);H(Gc,2,function(a){return a.toJavaScript()});H(Gc,'isDate',!0);H(Gc,'toNumber',function(a){return a.toJavaScript().getTime()});var Y=C.prototype;H(Y,'getBaseURI',function(a,b,c){if(c instanceof T)return c.baseURI});H(Y,'resolveURI',function(a,b,c){a=b[0];b=1<b.length?b[1]:c instanceof T&&c.baseURI;if(p(a)&&p(b)&&p(a=ia(a,b)))return a});H(Y,'getDaysInMonth',function(a,b){var c=L(b[0]),d=L(b[1],1,12);if(void 0!==c&&void 0!==d)return ka(c,d)});
H(Y,'getDayOfWeek',function(a,b){var c=L(b[0]),d=L(b[1],1,12),e=L(b[2],1,31);if(void 0!==c&&void 0!==d&&void 0!==e){var f=new Date([('0000'+c).slice(-4),('00'+d).slice(-2),('00'+e).slice(-2)].join('-'));if(f.getFullYear()===c&&f.getMonth()===d-1&&f.getDate()===e)return f.getDay()||7}});H(Y,'getWeekDayNameShort',void 0);H(Y,'getWeekDayNameLong',void 0);H(Y,'getMonthNameShort',void 0);H(Y,'getMonthNameLong',void 0);
H(Y,'getMin',function(a,b){for(var c,d,e=[];b.length;)if(c=b.shift(),d=K(c),void 0!==d){if(!e.length||d<e[0])e=[d,c]}else c instanceof B&&Array.prototype.push.apply(b,c.getValues());return e[1]});H(Y,'getMax',function(a,b){for(var c,d,e=[];b.length;)if(c=b.shift(),d=K(c),void 0!==d){if(!e.length||d>e[0])e=[d,c]}else c instanceof B&&Array.prototype.push.apply(b,c.getValues());return e[1]});
H(Y,'range',function(a,b){var c,d=1,e=[],f=L(b[0]);if(void 0!==f){if(1<b.length){if(c=L(b[1]),d=L(b[2]),void 0===d||1>d)d=1}else 0>f?(c=0,f+=1):0<f&&(c=f-1,f=0);if(void 0!==c)if(f<c)for(;f<=c;)e.push(f),f+=d;else for(;f>=c;)e.push(f),f-=d}return e});H(Y,'getUniqueId',function(){return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(a){var b=16*Math.random()|0;return('x'===a?b:b&3|8).toString(16)})},1);
H(Y,'getRand',function(a,b){var c=b[0],d=b[1],c=L(c),d=L(d);void 0===c&&(c=0);void 0===d&&(d=Math.pow(2,32)-1);c>d&&(c=[d,d=c][0]);return Math.floor(Math.random()*(d-c+1))+c},1);H(Y,'loadText',function(a,b,c,d){return hc(b[0],d,b[1],c)});H(Y,'loadJSON',function(a,b,c,d){return jc(b[0],d,b[1],c)});H(Y,'require',function(a,b,c,d){return kc(b[0],d,b[1],c)});H(Y,'eval',function(a,b,c,d){a=b[0];var e=b[1];b=b[2];if(p(a)){p(b)||(b=c.baseURI);try{a=Eb(a,b)}catch(f){}c=new T(b,e,c.M);A(a,c,d)}else d()});
H(Y,'wait',function(a,b,c,d){a=L(b.shift(),0);var e=b.shift();e instanceof y||(e=new y([],e,c));void 0===a?e.call(b,c,d):setTimeout(function(){e.call(b,c,d)},a)});function Hc(){try{var a=Error.prepareStackTrace;Error.prepareStackTrace=function(a,b){return b};var b=Error();Error.captureStackTrace(b,arguments.callee);var c=b.stack;Error.prepareStackTrace=a;return c[1].getFileName()}catch(d){return'undefined'===typeof window?'':window.location.href}}function Z(a,b){var c=Hc();b=p(b)?ia(b,c):c;a=a instanceof lc?a.getAST():Eb(a,b);return new lc(a,b)}Z.R_JS=pa;Z.R_HISTONE=qa;Z.R_STRING=ra;Z.R_SELF=sa;Z.M_GET=0;Z.M_CALL=1;Z.M_TOJS=2;Z.M_UNEVAL=3;Z.V_CLEAN=0;
Z.V_DIRTY=1;Z.V_NORET=2;Z.toJSON=Da;Z.toString=J;Z.toNumber=K;Z.toBoolean=I;Z.toJavaScript=Ea;Z.toHistone=G;Z.register=H;Z.unregister=function(a,b){if(!E.has(a))return!1;var c=E.get(a);if(!c.hasOwnProperty(b=String(b)))return!1;delete c[b];Object.keys(c).length||E['delete'](a);return!0};Z.invoke=Ca;Z.global=Fa;Z.Base=w;Z.Undefined=ua;Z.Null=va;Z.Boolean=Ga;Z.Number=Ha;Z.String=Ia;Z.RegExp=Ja;Z.Macro=y;Z.Array=B;Z.Date=D;Z.Global=C;Z.version='3.1.20';Z.setLanguage=function(){};
Z.setCache=function(a){ac=!!a};Z.clearCache=function(){Zb={}};Z.loadText=hc;Z.loadJSON=jc;Z.require=kc;Z.setResourceLoader=function(a){r(a)&&(Yb=a)};return Z;})();
return Histone;